### ISSUE TITLE
upload question doesn't support decimal values

### ISSUE THREAD

**Issue by hawkrobe** [longouyang/nosub#2]
When you run `nosub -p upload` it asks 

```
How long do you want to run the HIT?
You can answer in seconds, minutes, hours, days, or weeks and you can always add more time using nosub add.
```

If you give a non-integer response like `1.5 hours` it makes it expire in *five* hours.

**Comment by longouyang** [comment]
This should be fixed by 46332cbf2da1ae484529368ffa296431c2a11f73
