### ISSUE TITLE
insufficient funds in account prevents from expiring hit 

### ISSUE THREAD

**Issue by mcmeyers** [longouyang/nosub#3]
Hi! I have been using nosub in batch mode, and tried to run a large number of assignments (n=240). 12 batches uploaded (displaying preview links/hit ids as usual), but then I received an error that `This Requester has insufficient funds in their account to complete this transaction. Please visit https://requester.mturk.com/prepayments/new to purchase Prepaid HITs`. It seems like nosub uploaded as many batches as it could before running out of funds. 

The issue is that after I received this error, none of the nosub commands (status, expire, etc.) worked, so I was unable to check the status of the batches that had been created or expire the hit. I received this error message: 
```
$ nosub -p status
Running on production
/usr/local/lib/node_modules/nosub/src/methods.js:735
    return HITStatus(creationData.HITId, mtc).then(function(metadata) {
                                  ^

TypeError: Cannot read property 'HITId' of undefined
    at Object.status (/usr/local/lib/node_modules/nosub/src/methods.js:735:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/nosub/src/index.js:69:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```
However, the 12 batches of data that were uploaded before I received the "insufficient funds" error ran through turk without any issues (due to my task setup, I was able to access the data externally). This must only be a problem with batch mode. 

Another difference I noted was that with cosub, you were told how much money the task would cost, 
but it seems like this feature is not present in nosub (at least in batch mode). It was a helpful feature, so it would be great if it were added again. 

Thanks so much for your help!

**Comment by longouyang** [comment]
This definitely needs to be fixed.

It's going to take a little while, though. We need to check that the user balance is sufficient first before creating all the batches, but the current architecture doesn't play well with making multiple requests to the AWS servers. So I'll have to refactor a bunch of code to better support asynchrony (i.e., move from promises to `async/await`).

**Comment by hawkrobe** [comment]
just wanted to give a +1 for this -- just ran into the same issue and it puts me in a tricky position of having a bunch of turkers completing a HIT but `nosub` not giving me a handle to download their results (and thus no way to bonus them)

**Comment by longouyang** [comment]
I landed preliminary support for this checking in 352014b6952cceb1158348d53902ec7d5bbbd340

Right now it only checks your balance when initially creating the HIT(s) but not when adding additional assignments for an existing HIT

**Comment by longouyang** [comment]
Now it also checks balance before adding assignments to an existing HIT -- 79cc35d 

Lemme know if you encounter any issues

**Comment by hawkrobe** [comment]
huzzah!! thanks, long!

**Comment by longouyang** [comment]
It sounds like there haven't been any further issues, so I'm closing for now.
