### ISSUE TITLE
handle mturk migration to AWS Billing

### ISSUE THREAD

**Issue by hawkrobe** [longouyang/nosub#8]
# The problem

Amazon continues to deprecate and retire mturk features left and right, and the most recent on the chopping block looks like their system for maintaining a balance for [pre-paid HITs](https://blog.mturk.com/amazon-mechanical-turk-enables-aws-billing-for-requesters-f778b1368bce). They're suggesting you 'Enable AWS Billing', and if you click this button, they won't let you go back to pre-paid HITs. I also believe new accounts are required to use AWS Billing by default? 

<img width="1330" alt="CleanShot 2020-12-30 at 00 28 40@2x" src="https://user-images.githubusercontent.com/5262024/103336613-fb040980-4a35-11eb-8c64-2ed21deb790e.png">

# Implications for nosub

One of my collaborators accidentally switched over to AWS Billing and reported running into some troubles with nosub. I haven't explored it thoroughly, but most obviously, it will cause problems for the `balance` feature, which may need to catch an error if the balance doesn't exist.

**Comment by longouyang** [comment]
Sorry for the delay - at some point I disabled email notifications from Github, so this got lost in the void for a bit.

I just pushed a change - can you have your collaborator reinstall nosub and run commands like this?

```
AWS_BILLING=1 nosub add 30 assignments and 1 day
```

(i.e., running commands as usual but replacing `nosub` with `AWS_BILLING=1 nosub`)

If that doesn't work, could you have them shoot me an email? I'll need their help debugging this as I haven't upgraded my account yet

**Comment by hawkrobe** [comment]
thanks so much, @longouyang -- I'll have them try it out and update you soon!
